### ISSUE TITLE
Support change_table

### ISSUE THREAD

**Issue by khiav223577** [betesh/active_record-postgres-constraints#34]
`t.check_constraint` only works in `create_table`. It would be nice to be able to use it in [change_table](https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/change_table) block.
For example: 
```rb
change_table :people do |t|
  t.check_constraint title: ['Mr.', 'Mrs.', 'Dr.'] # add constraint
end
```

**Comment by betesh** [comment]
This gem is deprecated.
