### ISSUE TITLE
README about the constraint name

### ISSUE THREAD

**Issue by masasakano** [betesh/active_record-postgres-constraints#36]
It seems the methods of this Gem like `add_check_constraint` accept a constraint name as the second argument, if specified. If the name is specified explicitly, rollback seems to be a doddle (at least in Rails 6.0)! I think it is worth mentioning in README. An example of a migration file follows. Anyway, thank you for the great Gem! 

```ruby
class AddCheckConstraintsToWorkers < ActiveRecord::Migration[6.0]
  def change
    add_check_constraint :workers, 'check_workers_on_birth_month', "birth_month IS NULL OR birth_month BETWEEN 1 AND 12"
  end
end
```

**Comment by betesh** [comment]
@masasakano I apologize but I'm not familiar with the word "doddle."  Feel free to open a PR improving the README!

**Comment by betesh** [comment]
This gem is deprecated.
