### ISSUE TITLE
Constraint names should be consistent/deterministic

### ISSUE THREAD

**Issue by robotfelix** [betesh/active_record-postgres-constraints#5]
The line below means that if the same migration is run on multiple machines/databases, then each will get a constraint with a different name:
https://github.com/on-site/active_record-postgres-constraints/blob/beaebe651f4a46facf71812d56897ad5ac05812c/lib/active_record/postgres/constraints.rb#L40

I like the way that Rails creates a descriptive and consistent name for indexes automatically ([code is here](https://github.com/rails/rails/blob/054893d574f9c5eebc13d3749680f3a264e4b57d/activerecord/lib/active_record/connection_adapters/abstract/schema_statements.rb#L816)), and think it would be an improvement to copy this behaviour here. Something like `constrain_foos_on_bar_and_baz`.

If any of the following are true:
1. The conditions were specified in SQL so we can't easily tell what columns are used; or
2. The name would be too long; or
3. There is already a constraint with the same name;

then an error can be raised and the developer instructed to specify a name for the condition manually (also consistent with Rails behaviour).

I think this would be a good improvement, and reduce the potential for confusion caused by inconsistent constraint names. Do you agree with my thoughts here?

**Comment by betesh** [comment]
I agree and would welcome a PR.

**Comment by betesh** [comment]
This gem is deprecated.
